name: flutter_gpt_chatbot
description: A chatbot with GPT, STT and TTS

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_tts: ^4.2.2
  speech_to_text: ^7.0.0
